global-traffic-handler:
  scheduled-thread-pool-core-pool-size: 4

player-traffic-shaping:
  avg:
    writeLimit: 1413120
    min-duration: 25
  burst:
    writeLimit: 3145728
    max-duration: 8

send-traffic-rule-update-notification: true

ignored-servers:
  - lobby

# 数据库配置
database:
  # 使用 MySQL 存储数据，false 则直接崩溃
  mysql: true
  # 下面的配置应该就不用说了吧
  host: localhost
  port: 3306
  database: riatraffic
  user: root
  password: passwd
  # 表前缀
  prefix: "riatraffic_"
  # 使用 SSL
  usessl: false
  # 额外配置
  properties:
    connection-timeout: 60000
    validation-timeout: 3000
    idle-timeout: 60000
    login-timeout: 10
    maxLifeTime: 60000
    maximum-pool-size: 8
    minimum-idle: 2
    cachePrepStmts: true
    prepStmtCacheSize: 250
    prepStmtCacheSqlLimit: 2048
    useUnicode: true
    characterEncoding: utf8
    allowPublicKeyRetrieval: true